### ISSUE TITLE
CRAN submission ToDo list

### ISSUE THREAD

**Issue by nevrome** [ropensci/c14bazAAR#116]
Important info in: https://r-pkgs.org/release.html, https://cran.r-project.org/doc/manuals/r-devel/R-exts.html

**Pre-submission**
- [x] The package works and all functions are usable
- [x] The package documentation is up-to-date and represents the functions correctly
- [x] The test coverage of the package functions is sufficient
- [x] `DESCRIPTION` is up-to-date with the latest version number and database list
- [x] `README.md` is up-to-date
- [x] `News.md` is up-to-date and includes the latest changes
- [x] Package checks ran and did not yield any ERRORS, WARNINGS or NOTES (or at least the NOTES are addressed in the `cran-comments.md`)
    - [x] locally (`devtools::check()`)
    - [x] rhub (`devtools::check_rhub(email = ...)`)
    - [x] winbuilder (`devtools::check_win_release(email = ....)` + `devtools::check_win_devel(email = ....)`)
- [x] `cran-comments.md` is up-to-date and fits to the current submission process
- [x] Spellcheck with `devtools::spell_check()` ran and did yield not only false-positives
- [x] `codemeta.json` is up-to-date (can be updated with `codemetar::write_codemeta()`)
- [x] `inst/CITATION` is up-to-date
- [x] The package does not make external changes without explicit user permission. It does not write to the file system, change options, install packages, quit R, send information over the internet, open external software, etc.
- [ ] No reverse dependencies break because of the new package version (`devtools::revdep_check()`)

**Submission**
The actual submission should be done by the package maintainer with `devtools::release()`. In case of a resubmission `devtools::submit_cran()` spares you all the questions in `devtools::release()`.

**Post-submission**
- [ ] create a new release on Github
- [ ] add the .9000 suffix to the `Version` field in the `DESCRIPTION` to indicate that this is a development version
- [ ] create a new heading in `NEWS.md`

**Comment by dirkseidensticker** [comment]
notes:
* rhub run using:
```r
rhub::check(
platform="windows-x86_64-devel",
env_vars=c(R_COMPILE_AND_INSTALL_PACKAGES = "always")
)
```
in order to avoid error(s): `Error in loadNamespace(name) : there is no package called 'utf8'` (see https://github.com/r-hub/rhub/issues/367#issuecomment-621757715)

**Comment by nevrome** [comment]
IMHO CRAN submission is permanently cancelled, now that https://ropensci.r-universe.dev/ exists.

But we should absolutely add the install command 

```
install.packages("c14bazAAR", repos = c(ropensci = "https://ropensci.r-universe.dev", CRAN = "https://cloud.r-project.org"))
```

to the README (it should come with binaries) and release 1.3.0.

Thoughts, @dirkseidensticker?

**Comment by dirkseidensticker** [comment]
need to dig into this a bit more, but I guess your are right that https://ropensci.r-universe.dev/ is a good way to go forward 👍

**Comment by nevrome** [comment]
Alright! This new setup is taking shape in my mind. We should make sure the master branch is always in perfect shape - probably by not pushing to it directly anymore for everything but very minor changes. 

We should also adopt [semantic versioning](https://semver.org/) which will cause a much faster turnover of versions. Maybe we should increment the version number with each commit. Can be done with a git hook. I already use this for some projects.

**Comment by nevrome** [comment]
The CRAN submission TODO-List should go into the README in the dev section
